[targets]
alma-rhcsa ansible_host=192.168.122.193
alma-target-02 ansible_host=192.168.122.67
alma-security ansible_host=192.168.122.149
freeipa-lab  ansible_host=192.168.122.143

[rhcsa]
alma-rhcsa

[rhce]
alma-target-02

[security]
alma-security

[production]
alma-rhcsa
alma-target-02

[freeipa]
freeipa-lab

[all:vars]
ansible_user=labadmin
ansible_ssh_private_key_file=~/.ssh/datenmaniak
ansible_python_interpreter=/usr/bin/python3

# Variables específicas por grupo
[production:vars]
update_serial=1  # Actualizar de a uno en producción

[security:vars]
update_serial=3  # En seguridad podemos actualizar de a 3