[targets]
alma-rhcsa ansible_host=192.168.122.193
alma-target-02 ansible_host=192.168.122.67
alma-security ansible_host=192.168.122.149

[targets:vars]
ansible_user=labadmin
ansible_ssh_private_key_file=~/.ssh/datenmaniak
ansible_python_interpreter=/usr/bin/python3
